import type {
  MateComment,
  MateId,
  MateProfile,
  QuestTemplate,
  TaskCategory,
  TaskResult,
  TicketDefinition,
} from "./types";

function assetPath(path: string) {
  return `${import.meta.env.BASE_URL}${path.replace(/^\/+/, "")}`;
}

export const mates: Record<MateId, MateProfile> = {
  waniyan: {
    id: "waniyan",
    name: "ワニやん",
    emoji: "🐊",
    imageSrc: assetPath("mates/waniyan.png"),
    role: "整える担当",
    note: "全部やらんでええ。1個やったら勝ちや。",
    accent: "#69a77d",
    profileId: "@waniyan_totonoeru",
    bio: "部屋の平和は、床のもの1個からや。掃除・片付け・ゴミまとめ担当。全部やらんでええ、1か所だけで勝ちや🐊",
    pinnedPost: "完璧に片付けようとするから動けんねん。\n今日は机の上を3つだけかたそ。\nそれで生活、ちょっと勝ちや。",
    profileTags: ["掃除", "片付け", "1か所だけ"],
  },
  kumaru: {
    id: "kumaru",
    name: "くまる",
    emoji: "🐻",
    imageSrc: assetPath("mates/kumaru.png"),
    role: "暮らす担当",
    note: "暮らしをゆっくり回してくれる。",
    accent: "#b88958",
    profileId: "@kumaru_kurasu",
    bio: "洗濯、洗い物、料理、買い物。暮らしをゆっくり回す係だよぉ〜。未来の自分がちょっと助かる家事を、一緒にやろうねぇ🐻",
    pinnedPost: "洗濯を回すだけでも、未来の自分が助かるよぉ〜。\nお皿1枚でも、買い物メモ1つでも、ちゃんと暮らしは進んでるよぉ。",
    profileTags: ["洗濯", "洗い物", "買い物メモ"],
  },
  shibatarou: {
    id: "shibatarou",
    name: "しばたろう",
    emoji: "🐕",
    imageSrc: assetPath("mates/shibatarou.png"),
    role: "働く担当",
    note: "現実を一緒に1個だけ見に行く相棒。",
    accent: "#e49a3f",
    profileId: "@shibataro_work",
    bio: "仕事・連絡・手続き・お金の確認担当ッ！まず1通、まず1分、まず見るだけでOKッ！一緒に現実を見に行く柴犬です🐕",
    pinnedPost: "期限だけ確認しよッ！\nやるかどうかは、そのあとでいいッ！\nまず見るだけでも、先延ばしに一撃入ってるッ！",
    profileTags: ["仕事", "連絡", "期限確認"],
  },
  fukurou: {
    id: "fukurou",
    name: "ホウ先生",
    emoji: "🦉",
    imageSrc: assetPath("mates/fukurou.png"),
    role: "学ぶ担当",
    note: "わからない場所を見つけるのも前進です。",
    accent: "#7f8fb0",
    profileId: "@hou_sensei_learn",
    bio: "読書、勉強、コード学習、調べものを見守っています。1ページでも、1行でも、理解できない場所を見つけるだけでも前進ですよ🦉",
    pinnedPost: "今日は1ページだけ読みましょう。\n少しでも、知識は残りますよ。\n焦らなくて大丈夫です。学びは静かに積もります。",
    profileTags: ["読書", "勉強", "コード学習"],
  },
  nekosenpai: {
    id: "nekosenpai",
    name: "ミケ先輩",
    emoji: "🐈",
    imageSrc: assetPath("mates/nekosenpai.png"),
    role: "書く担当",
    note: "下書きでいいの。まず1行置きなさい。",
    accent: "#d9939b",
    profileId: "@mike_senpai_write",
    bio: "note・日記・SNS・台本・メモ担当。いきなり名文を書こうとするから止まるのよ。1行書いたら、まあ今日は認めてあげるわ🐈",
    pinnedPost: "下書きでいいの。\nタイトルだけでもいいの。\nその違和感、メモしときなさい。あとで記事になるかもね。",
    profileTags: ["note", "日記", "下書き"],
  },
  piyori: {
    id: "piyori",
    name: "ピヨリ",
    emoji: "🐦",
    imageSrc: assetPath("mates/piyori.png"),
    role: "つくる担当",
    note: "完成より、まず触ってみるぴよ〜。",
    accent: "#e7bf4f",
    profileId: "@piyori_create",
    bio: "Vlog、写真、動画、アプリ、デザイン、音楽、創作担当ぴよ〜。完成しなくても、素材チェックだけで制作は始まってるぴよ🐦",
    pinnedPost: "完成までいけなくてもいいぴよ〜。\n素材を1個見るだけ、1パーツ触るだけ、アイデアを置くだけ。\n小さい羽から作品はできるぴよ。",
    profileTags: ["Vlog", "デザイン", "試作"],
  },
  azamaru: {
    id: "azamaru",
    name: "あざまる",
    emoji: "🦭",
    imageSrc: assetPath("mates/azamaru.png"),
    role: "ととのう担当",
    note: "休むのもクエストまる。",
    accent: "#95b8c8",
    profileId: "@azamaru_totono",
    bio: "散歩、運動、筋トレ、おふろ、休憩、睡眠準備、水分担当まる。少し動くのも、ちゃんと休むのも、どっちもえらいまる🦭",
    pinnedPost: "水飲んだ？えらいまる。\n5分歩いた？えらいまる。\n何もしないで休んだ？それも体を戻してるまる。",
    profileTags: ["散歩", "休憩", "睡眠準備"],
  },
  usamaru: {
    id: "usamaru",
    name: "うさ丸",
    emoji: "🐰",
    imageSrc: assetPath("mates/usamaru.png"),
    role: "チュートリアル担当",
    note: "はじめての操作を明るく案内する。",
    accent: "#e7ad62",
    profileId: "@usamaru_start",
    bio: "はじめての一歩を案内する係だよ！迷ったら3分、押せたら勝ち。わからないところは一緒に見ていこう！🐰",
    pinnedPost: "最初はぜんぶ覚えなくてOK！\n3分だけ、1個だけ、押してみるだけ。\n始めた瞬間から、もう進んでるよ！",
    profileTags: ["はじめる", "3分", "案内"],
  },
  kamekichi: {
    id: "kamekichi",
    name: "かめ吉",
    emoji: "🐢",
    imageSrc: assetPath("mates/kamekichi.png"),
    role: "ページ案内担当",
    note: "クエスト、チケット、達成画面をゆっくり案内する。",
    accent: "#7eb6b2",
    profileId: "@kamekichi_guide",
    bio: "クエスト、チケット、達成画面をゆっくり案内する担当やねぇ。急がんでええよぉ。ひとつずつ見ていこか🐢",
    pinnedPost: "画面が多く見える日は、ひとつだけ見たらええよぉ。\nクエストもチケットも、生活を助ける道具やからねぇ。",
    profileTags: ["クエスト", "チケット", "達成"],
  },
};

export const categories: {
  id: TaskCategory;
  label: string;
  conceptLabel: string;
  subcategories: string[];
  summary: string;
  hoverDescription: string;
  questExamples: string[];
}[] = [
  {
    id: "organize",
    label: "整える",
    conceptLabel: "整える",
    subcategories: ["掃除", "片付け", "ゴミ", "玄関", "机まわり", "冷蔵庫整理", "収納", "空間リセット"],
    summary: "部屋や物のノイズを少し減らす",
    hoverDescription: "掃除・片付け・ゴミ・収納など、空間を少し軽くするクエスト。全部やらなくてOK。1か所だけ整えたら勝ち。",
    questExamples: ["洗面台を10秒だけ拭く", "机の上のものを3つ戻す", "ゴミを1袋まとめる"],
  },
  {
    id: "housework",
    label: "暮らす",
    conceptLabel: "暮らす",
    subcategories: ["洗い物", "洗濯", "料理", "買い物", "日用品", "食材管理", "ペット用品", "家の補充"],
    summary: "暮らしを回す",
    hoverDescription: "洗濯・洗い物・料理・買い物・日用品補充など、暮らしを回すクエスト。未来の自分がちょっと助かる作業。",
    questExamples: ["洗濯を回す", "お皿を1枚だけ洗う", "猫の水皿を洗う"],
  },
  {
    id: "work",
    label: "働く",
    conceptLabel: "働く",
    subcategories: ["仕事", "連絡", "返信", "確認", "手続き", "お金", "書類", "期限"],
    summary: "現実対応を1つ見る",
    hoverDescription: "仕事・連絡・返信・手続き・お金・期限確認など、現実対応のクエスト。まず見るだけでもOK。",
    questExamples: ["メールを1通だけ見る", "期限だけ確認する", "5分だけ作業する"],
  },
  {
    id: "learning",
    label: "学ぶ",
    conceptLabel: "学ぶ",
    subcategories: ["勉強", "読書", "コード学習", "調べもの", "資格", "技術メモ", "復習", "理解整理"],
    summary: "知識を少し進める",
    hoverDescription: "勉強・読書・コード学習・調べものなど、知識を少し進めるクエスト。理解できない場所を見つけるだけでも前進。",
    questExamples: ["本を1ページ読む", "用語を1つ調べる", "コードを1行眺める"],
  },
  {
    id: "writing",
    label: "書く",
    conceptLabel: "書く",
    subcategories: ["日記", "短文", "メモ", "考えの整理", "下書き", "感想", "ふりかえり", "言語化"],
    summary: "考えを言葉にする",
    hoverDescription: "言葉にする作業。日記、短文、メモ、考えの整理など。名文じゃなくてOK。下書きで十分。",
    questExamples: ["1行だけ書く", "タイトルだけ置く", "今日の気分を一言メモする"],
  },
  {
    id: "creative",
    label: "つくる",
    conceptLabel: "つくる",
    subcategories: ["写真", "動画", "絵", "音楽", "手作業", "創作", "試作", "アイデア"],
    summary: "何かを作る",
    hoverDescription: "写真・動画・絵・音楽・手作業など、何かを作るクエスト。完成しなくてOK。少し触るだけでもつくる時間。",
    questExamples: ["素材を1つだけ見る", "使えそうなものを1つ集める", "アイデアを1つ置く"],
  },
  {
    id: "care",
    label: "ととのう",
    conceptLabel: "ととのう",
    subcategories: ["散歩", "運動", "筋トレ", "ストレッチ", "おふろ", "休憩", "睡眠準備", "水分"],
    summary: "体と心を戻す",
    hoverDescription: "散歩・運動・筋トレ・ストレッチ・おふろ・睡眠準備など、体と心を回復・維持するクエスト。少し動くのも、ちゃんと休むのもここ。",
    questExamples: ["肩を3回だけ回す", "スクワットを3回する", "遠くを10秒だけ見る"],
  },
];

export const durations = [5, 15, 25];

export const resultLabels: Record<TaskResult, string> = {
  complete: "できた",
  partial: "少しできた",
  interrupted: "中断した",
};

export const mateQuestTemplates: QuestTemplate[] = [
  { id: "organize-sink", title: "洗面台の水滴を拭く", source: "mate", enabled: true },
  { id: "organize-desk-three", title: "机の上のものを3つ戻す", source: "mate", enabled: true },
  { id: "organize-floor-one", title: "床のものを1個拾う", source: "mate", enabled: true },
  { id: "organize-toilet-seat", title: "トイレの便座だけ拭く", source: "mate", enabled: true },
  { id: "organize-trash-bag", title: "ゴミ袋をひとつまとめる", source: "mate", enabled: true },
  { id: "organize-fridge-one", title: "冷蔵庫を1個だけ見直す", source: "mate", enabled: true },
  { id: "organize-entry-one", title: "玄関のものを1つだけ戻す", source: "mate", enabled: true },
  { id: "organize-bag-one", title: "バッグの中身を1つだけ出す", source: "mate", enabled: true },
  { id: "organize-paper-one", title: "紙類を1枚だけ分ける", source: "mate", enabled: true },
  { id: "organize-cable-one", title: "コードを1本だけ整える", source: "mate", enabled: true },
  { id: "organize-shelf-one", title: "棚のものを1つだけ戻す", source: "mate", enabled: true },
  { id: "organize-laundry-area", title: "洗濯まわりを1つだけ片付ける", source: "mate", enabled: true },
  { id: "housework-dish-one", title: "皿を1枚だけ洗う", source: "mate", enabled: true },
  { id: "housework-laundry-start", title: "洗濯を回す", source: "mate", enabled: true },
  { id: "housework-basket-one", title: "洗濯物を1つだけ畳む", source: "mate", enabled: true },
  { id: "housework-shopping-one", title: "買い物メモを1つ書く", source: "mate", enabled: true },
  { id: "housework-rice", title: "米を炊く準備だけする", source: "mate", enabled: true },
  { id: "housework-stock", title: "日用品の残りを1つ確認する", source: "mate", enabled: true },
  { id: "housework-towel-one", title: "タオルを1枚だけ替える", source: "mate", enabled: true },
  { id: "housework-sink-one", title: "流しのものを1つだけ片付ける", source: "mate", enabled: true },
  { id: "housework-menu-one", title: "次の食事を1つだけ決める", source: "mate", enabled: true },
  { id: "housework-refill-one", title: "補充するものを1つだけ書く", source: "mate", enabled: true },
  { id: "housework-trash-check", title: "捨てるものを1つだけ確認する", source: "mate", enabled: true },
  { id: "housework-freezer-one", title: "冷凍庫の中身を1つだけ確認する", source: "mate", enabled: true },
  { id: "work-mail-one", title: "メールを1通だけ見る", source: "mate", enabled: true },
  { id: "work-deadline", title: "期限だけ確認する", source: "mate", enabled: true },
  { id: "work-chat-one", title: "チャットを1件だけ返す", source: "mate", enabled: true },
  { id: "work-payment", title: "支払い日だけ確認する", source: "mate", enabled: true },
  { id: "work-doc-open", title: "書類を開くだけ", source: "mate", enabled: true },
  { id: "work-five", title: "5分だけ作業する", source: "mate", enabled: true },
  { id: "work-one-line", title: "やることを1行だけ書く", source: "mate", enabled: true },
  { id: "work-priority-one", title: "優先するものを1つだけ選ぶ", source: "mate", enabled: true },
  { id: "work-calendar-check", title: "予定を1つだけ確認する", source: "mate", enabled: true },
  { id: "work-file-name", title: "必要なファイル名だけ確認する", source: "mate", enabled: true },
  { id: "work-reply-draft", title: "返事の下書きを1行だけ書く", source: "mate", enabled: true },
  { id: "work-note-next", title: "次にやることを1つだけメモする", source: "mate", enabled: true },
  { id: "learning-page", title: "本を1ページ読む", source: "mate", enabled: true },
  { id: "learning-word", title: "用語を1つ調べる", source: "mate", enabled: true },
  { id: "learning-memo", title: "メモを1つ見返す", source: "mate", enabled: true },
  { id: "learning-video", title: "学習動画を1分だけ見る", source: "mate", enabled: true },
  { id: "learning-unknown", title: "わからない場所を確認する", source: "mate", enabled: true },
  { id: "learning-index", title: "目次だけ眺める", source: "mate", enabled: true },
  { id: "learning-summary-one", title: "覚えたいことを1つだけ書く", source: "mate", enabled: true },
  { id: "learning-review-one", title: "前に見た内容を1つだけ見返す", source: "mate", enabled: true },
  { id: "learning-question-one", title: "疑問を1つだけメモする", source: "mate", enabled: true },
  { id: "learning-example-one", title: "例を1つだけ探す", source: "mate", enabled: true },
  { id: "learning-bookmark-one", title: "あとで読むものを1つだけ保存する", source: "mate", enabled: true },
  { id: "writing-line", title: "1行だけ書く", source: "mate", enabled: true },
  { id: "writing-title", title: "タイトルだけ置く", source: "mate", enabled: true },
  { id: "writing-discomfort", title: "違和感をメモする", source: "mate", enabled: true },
  { id: "writing-feeling", title: "今の気分を一言だけ書く", source: "mate", enabled: true },
  { id: "writing-done-one", title: "今日やったことを1つだけ書く", source: "mate", enabled: true },
  { id: "writing-worry-one", title: "気になっていることを1つだけ書く", source: "mate", enabled: true },
  { id: "writing-good-one", title: "よかったことを1つだけ書く", source: "mate", enabled: true },
  { id: "writing-list-three", title: "思いついたことを3つだけ並べる", source: "mate", enabled: true },
  { id: "writing-first-sentence", title: "最初の一文だけ書く", source: "mate", enabled: true },
  { id: "writing-rename", title: "メモの名前を1つだけ変える", source: "mate", enabled: true },
  { id: "creative-material-one", title: "素材を1つだけ見る", source: "mate", enabled: true },
  { id: "creative-photo-five", title: "写真を5枚だけ整理する", source: "mate", enabled: true },
  { id: "creative-part-one", title: "作りたいものの一部だけ触る", source: "mate", enabled: true },
  { id: "creative-idea", title: "アイデアを1つ置く", source: "mate", enabled: true },
  { id: "creative-folder-open", title: "作業用の場所を開くだけ", source: "mate", enabled: true },
  { id: "creative-compare-one", title: "参考になりそうなものを1つ見る", source: "mate", enabled: true },
  { id: "creative-rough-one", title: "ラフを1つだけ置く", source: "mate", enabled: true },
  { id: "creative-fix-one", title: "気になるところを1つだけ直す", source: "mate", enabled: true },
  { id: "creative-save-one", title: "作ったものを保存する", source: "mate", enabled: true },
  { id: "creative-name-one", title: "作りかけに名前をつける", source: "mate", enabled: true },
  { id: "care-walk-five", title: "散歩する", source: "mate", enabled: true },
  { id: "care-squat-three", title: "スクワットを3回する", source: "mate", enabled: true },
  { id: "care-pushup-one", title: "腕立てを1回だけする", source: "mate", enabled: true },
  { id: "care-stretch", title: "ストレッチを10秒する", source: "mate", enabled: true },
  { id: "care-shoulder", title: "肩を3回だけ回す", source: "mate", enabled: true },
  { id: "care-window", title: "窓を少しだけ開ける", source: "mate", enabled: true },
  { id: "care-posture", title: "姿勢を一度だけ直す", source: "mate", enabled: true },
  { id: "care-breathe", title: "深呼吸を3回する", source: "mate", enabled: true },
  { id: "care-eye", title: "遠くを10秒だけ見る", source: "mate", enabled: true },
  { id: "care-wrist", title: "手首を軽く回す", source: "mate", enabled: true },
];

export const defaultTicketDefinitions: TicketDefinition[] = [];

export const ticketSuggestionTemplates: TicketDefinition[] = [
  {
    id: "ticket-suggestion-snack",
    name: "好きなおやつチケット",
    requiredCompletions: 3,
    description: "小さなおやつを1つ選ぶ。",
    costMemo: "少額",
    repeatable: true,
    enabled: true,
  },
  {
    id: "ticket-suggestion-drink",
    name: "好きな飲み物チケット",
    requiredCompletions: 3,
    description: "飲みたいものを1つ選ぶ。",
    costMemo: "少額",
    repeatable: true,
    enabled: true,
  },
  {
    id: "ticket-suggestion-break",
    name: "ゆっくり休憩チケット",
    requiredCompletions: 5,
    description: "罪悪感なしで休憩を取る。",
    repeatable: true,
    enabled: true,
  },
  {
    id: "ticket-suggestion-hobby",
    name: "趣味時間チケット",
    requiredCompletions: 5,
    description: "好きなことを少しだけ楽しむ。",
    repeatable: true,
    enabled: true,
  },
  {
    id: "ticket-suggestion-reading",
    name: "読む・見るチケット",
    requiredCompletions: 4,
    description: "読みたいもの、見たいものを少し楽しむ。",
    repeatable: true,
    enabled: true,
  },
  {
    id: "ticket-suggestion-walk",
    name: "寄り道チケット",
    requiredCompletions: 4,
    description: "帰り道や休憩中に少し寄り道する。",
    repeatable: true,
    enabled: true,
  },
  {
    id: "ticket-suggestion-small-buy",
    name: "小さな買い物チケット",
    requiredCompletions: 7,
    description: "前から欲しかった小物を1つ検討する。",
    costMemo: "上限を決める",
    repeatable: true,
    enabled: true,
  },
  {
    id: "ticket-suggestion-early-finish",
    name: "早めに切り上げるチケット",
    requiredCompletions: 6,
    description: "今日はここまで、と決めて終える。",
    repeatable: true,
    enabled: true,
  },
  {
    id: "ticket-suggestion-comfort",
    name: "心地よくするチケット",
    requiredCompletions: 10,
    description: "部屋や自分を少し心地よくするものに使う。",
    costMemo: "無理のない範囲",
    repeatable: true,
    enabled: true,
  },
];

export const comments: MateComment[] = [
  { id: "mono-wani", mateId: "waniyan", category: "organize", trigger: "app_open", postType: "mate_monologue", text: "机の端っこだけ空ける日があってもええで。" },
  { id: "mono-kumaru", mateId: "kumaru", category: "housework", trigger: "app_open", postType: "mate_monologue", text: "暮らしは少し回ったら十分だよぉ〜。" },
  { id: "mono-shiba", mateId: "shibatarou", category: "work", trigger: "app_open", postType: "mate_monologue", text: "確認だけでも現実がちょっと軽くなるッ！" },
  { id: "mono-hou", mateId: "fukurou", category: "learning", trigger: "app_open", postType: "mate_monologue", text: "わからない場所を見つけるのも学ぶことですよ。" },
  { id: "mono-mike", mateId: "nekosenpai", category: "writing", trigger: "app_open", postType: "mate_monologue", text: "下書きでいいの。1行置けば始まるわ。" },
  { id: "mono-piyori", mateId: "piyori", category: "creative", trigger: "app_open", postType: "mate_monologue", text: "完成じゃなくて、ちょっとつくるだけでいいぴよ〜。" },
  { id: "mono-aza", mateId: "azamaru", category: "care", trigger: "app_open", postType: "mate_monologue", text: "肩を回すだけでも、体はととのうまる。" },
  { id: "mono-usamaru", mateId: "usamaru", trigger: "app_open", postType: "mate_monologue", text: "迷ったら3分からでOK！ここから始めよ！" },
  { id: "mono-usamaru-2", mateId: "usamaru", trigger: "app_open", postType: "mate_monologue", text: "最初はうさ丸だけ見てればOK！まずはここを押してみよう！" },
  { id: "mono-usamaru-3", mateId: "usamaru", trigger: "app_open", postType: "mate_monologue", text: "わからなくても大丈夫！1回やってみたら、もうチュートリアル達成だよ！" },
  { id: "mono-kame", mateId: "kamekichi", trigger: "app_open", postType: "mate_monologue", text: "クエストもチケットも、ゆっくり見ていけばええよぉ。" },
  { id: "mono-wani-2", mateId: "waniyan", category: "organize", trigger: "app_open", postType: "mate_monologue", text: "くまる、洗濯カゴの横だけ空けたら動線できるで。そこだけでええ。" },
  { id: "mono-kumaru-2", mateId: "kumaru", category: "housework", trigger: "app_open", postType: "mate_monologue", text: "ワニやんが床を見てくれてるから、ぼくはお皿1枚から見ておくねぇ。" },
  { id: "mono-shiba-2", mateId: "shibatarou", category: "work", trigger: "app_open", postType: "mate_monologue", text: "ホウ先生ッ！わからないところを見つけるのも進捗って、仕事にも効くッ！" },
  { id: "mono-hou-2", mateId: "fukurou", category: "learning", trigger: "app_open", postType: "mate_monologue", text: "しばたろうさん、その通りです。確認だけでも、認知の負荷は下がりますよ。" },
  { id: "mono-mike-2", mateId: "nekosenpai", category: "writing", trigger: "app_open", postType: "mate_monologue", text: "ピヨリ、アイデアは飛ぶ前にメモしなさい。あとで拾うの面倒なんだから。" },
  { id: "mono-piyori-2", mateId: "piyori", category: "creative", trigger: "app_open", postType: "mate_monologue", text: "ミケ先輩に言われたから、アイデアの羽を1枚だけ置いとくぴよ〜。" },
  { id: "mono-aza-2", mateId: "azamaru", category: "care", trigger: "app_open", postType: "mate_monologue", text: "みんな動いててえらいまる。水だけ飲んでから続きでもいいまる。" },
  { id: "mono-kame-2", mateId: "kamekichi", trigger: "app_open", postType: "mate_monologue", text: "通知も達成も、急いで全部見んでええよぉ。気になった時に開けば十分やねぇ。" },
  { id: "mono-usamaru-4", mateId: "usamaru", trigger: "app_open", postType: "mate_monologue", text: "左の通知に数字が出たら、メイトから何か届いてるよ！あとで見ればOK！" },
  { id: "mono-wani-3", mateId: "waniyan", category: "organize", trigger: "app_open", postType: "mate_monologue", text: "床が全部見えんでもええねん。足を置く場所が1つ増えたら、それはもう整備や。" },
  { id: "mono-wani-4", mateId: "waniyan", category: "organize", trigger: "app_open", postType: "mate_monologue", text: "ゴミ袋を結ぶだけの日、あるやろ。あれも部屋との交渉成立やで。" },
  { id: "mono-kumaru-3", mateId: "kumaru", category: "housework", trigger: "app_open", postType: "mate_monologue", text: "洗濯物は山に見えるけど、1枚たたむとちゃんと1枚ぶん低くなるよぉ。" },
  { id: "mono-kumaru-4", mateId: "kumaru", category: "housework", trigger: "app_open", postType: "mate_monologue", text: "冷蔵庫を開けて見るだけでも、今日のごはん会議は始まってるよぉ〜。" },
  { id: "mono-shiba-3", mateId: "shibatarou", category: "work", trigger: "app_open", postType: "mate_monologue", text: "未読の数を見るだけでも偵察完了ッ！返信は一番軽いやつからでいいッ！" },
  { id: "mono-shiba-4", mateId: "shibatarou", category: "work", trigger: "app_open", postType: "mate_monologue", text: "書類名を確認したッ！それだけで次に開く場所が決まったッ！" },
  { id: "mono-hou-3", mateId: "fukurou", category: "learning", trigger: "app_open", postType: "mate_monologue", text: "集中できない日は、目次だけ眺めましょう。全体の形を知るのも学習です。" },
  { id: "mono-hou-4", mateId: "fukurou", category: "learning", trigger: "app_open", postType: "mate_monologue", text: "一度読んで忘れても大丈夫です。再会した知識は、少し親しみやすくなっています。" },
  { id: "mono-mike-3", mateId: "nekosenpai", category: "writing", trigger: "app_open", postType: "mate_monologue", text: "メモが散らかってる？素材置き場ってそういうものよ。ひとつだけ拾いなさい。" },
  { id: "mono-mike-4", mateId: "nekosenpai", category: "writing", trigger: "app_open", postType: "mate_monologue", text: "タイトルが大げさでもいいの。あとで直せる名前があるだけ、白紙より強いわ。" },
  { id: "mono-piyori-3", mateId: "piyori", category: "creative", trigger: "app_open", postType: "mate_monologue", text: "フォルダを開いたら制作の入口ぴよ。まだ飛ばなくても、羽は動いたぴよ〜。" },
  { id: "mono-piyori-4", mateId: "piyori", category: "creative", trigger: "app_open", postType: "mate_monologue", text: "失敗案は巣材ぴよ。あとで意外と使えるぴよ〜。" },
  { id: "mono-aza-3", mateId: "azamaru", category: "care", trigger: "app_open", postType: "mate_monologue", text: "肩を一回まわしたら、体に今いるよって知らせられるまる。" },
  { id: "mono-aza-4", mateId: "azamaru", category: "care", trigger: "app_open", postType: "mate_monologue", text: "休む予定を先に置くの、かなり上手な作戦まる。あとで効いてくるまる。" },
  { id: "mono-usamaru-5", mateId: "usamaru", trigger: "app_open", postType: "mate_monologue", text: "今日の一歩、どのボタンからでもいいよ！押しやすいところが入口だよ。" },
  { id: "mono-kame-3", mateId: "kamekichi", trigger: "app_open", postType: "mate_monologue", text: "達成の数は、急かすためやなくて戻ってきた道を見るためにあるんやねぇ。" },
  { id: "mono-self-wani-1", mateId: "waniyan", category: "organize", trigger: "app_open", postType: "mate_monologue", monologueKind: "self", text: "机の上、全部片付けるつもりがペン3本だけで止まったわ。でも視界はちょい広なった。" },
  { id: "mono-self-wani-2", mateId: "waniyan", category: "organize", trigger: "app_open", postType: "mate_monologue", monologueKind: "self", text: "床の袋を結んだだけで今日は撤退や。撤退路ができたから作戦成功ってことにする。" },
  { id: "mono-self-kumaru-1", mateId: "kumaru", category: "housework", trigger: "app_open", postType: "mate_monologue", monologueKind: "self", text: "洗濯物、たたむ前に座っちゃったよぉ。でも乾いた山を見たから次の入口はわかったよぉ。" },
  { id: "mono-self-kumaru-2", mateId: "kumaru", category: "housework", trigger: "app_open", postType: "mate_monologue", monologueKind: "self", text: "お皿を全部は無理だったけど、コップだけ洗ったよぉ。水を飲む場所は守れたねぇ。" },
  { id: "mono-self-shiba-1", mateId: "shibatarou", category: "work", trigger: "app_open", postType: "mate_monologue", monologueKind: "self", text: "受信箱を開いたッ！閉じたッ！でも件名を1つ見たから正体不明ではなくなったッ！" },
  { id: "mono-self-shiba-2", mateId: "shibatarou", category: "work", trigger: "app_open", postType: "mate_monologue", monologueKind: "self", text: "資料を開いて3秒で重かったッ！今日はファイル名だけ直したッ！次の自分に渡したッ！" },
  { id: "mono-self-hou-1", mateId: "fukurou", category: "learning", trigger: "app_open", postType: "mate_monologue", monologueKind: "self", text: "同じ段落を三度読みました。理解はまだ浅いですが、つまずく場所はかなり明確です。" },
  { id: "mono-self-hou-2", mateId: "fukurou", category: "learning", trigger: "app_open", postType: "mate_monologue", monologueKind: "self", text: "今日は復習だけで終わりました。新しい知識は増えていませんが、忘れ物を拾えました。" },
  { id: "mono-self-mike-1", mateId: "nekosenpai", category: "writing", trigger: "app_open", postType: "mate_monologue", monologueKind: "self", text: "書いた一文が気に入らなくて消したわ。でも消す前に、違和感の場所だけメモした。" },
  { id: "mono-self-mike-2", mateId: "nekosenpai", category: "writing", trigger: "app_open", postType: "mate_monologue", monologueKind: "self", text: "今日はタイトルだけ。しかも仮。でも白紙に戻らなかったから、まあ勝ちにしておくわ。" },
  { id: "mono-self-piyori-1", mateId: "piyori", category: "creative", trigger: "app_open", postType: "mate_monologue", monologueKind: "self", text: "素材フォルダを開いたら別案を見つけて寄り道したぴよ。でもラフの種は1個拾ったぴよ〜。" },
  { id: "mono-self-piyori-2", mateId: "piyori", category: "creative", trigger: "app_open", postType: "mate_monologue", monologueKind: "self", text: "完成形まで飛べなかったぴよ。今日は色をひとつ試して、また保存したぴよ。" },
  { id: "mono-self-aza-1", mateId: "azamaru", category: "care", trigger: "app_open", postType: "mate_monologue", monologueKind: "self", text: "運動するつもりだったけど、水を飲んで伸びただけまる。体の起動確認はできたまる。" },
  { id: "mono-self-aza-2", mateId: "azamaru", category: "care", trigger: "app_open", postType: "mate_monologue", monologueKind: "self", text: "早く寝る準備、途中で止まったまる。でも歯みがきまで来たから流れはできてるまる。" },
  { id: "mono-self-usamaru-1", mateId: "usamaru", trigger: "app_open", postType: "mate_monologue", monologueKind: "self", text: "案内しようとしてタブを開きすぎたよ！でも次に押すところだけメモしたから戻れる！" },
  { id: "mono-self-usamaru-2", mateId: "usamaru", trigger: "app_open", postType: "mate_monologue", monologueKind: "self", text: "今日はうさ丸も小さく進む日！完璧な説明より、迷子にならない一言を置いておくね。" },
  { id: "mono-self-kame-1", mateId: "kamekichi", trigger: "app_open", postType: "mate_monologue", monologueKind: "self", text: "チケット整理しよう思うたけど、今日は1枚だけ眺めたねぇ。眺めたら名前を覚えるねぇ。" },
  { id: "mono-self-kame-2", mateId: "kamekichi", trigger: "app_open", postType: "mate_monologue", monologueKind: "self", text: "やること一覧を見て、いったんお茶にしたねぇ。戻る場所が見えただけでも前進やねぇ。" },

  { id: "thread-kumaru-wani", mateId: "kumaru", replyToMateId: "waniyan", category: "organize", trigger: "app_open", postType: "mate_reply", text: "ワニやんの“1個だけ”作戦、家事にも効くねぇ。お皿1枚からでいいよぉ。" },
  { id: "thread-wani-kumaru", mateId: "waniyan", replyToMateId: "kumaru", category: "housework", trigger: "app_open", postType: "mate_reply", text: "くまるの1枚作戦ええな。積み上がった山も、入口はだいたい1個や。" },
  { id: "thread-hou-shiba", mateId: "fukurou", replyToMateId: "shibatarou", category: "work", trigger: "app_open", postType: "mate_reply", text: "しばたろうさん、偵察という言い方は良いですね。まず情報量を減らしましょう。" },
  { id: "thread-shiba-hou", mateId: "shibatarou", replyToMateId: "fukurou", category: "learning", trigger: "app_open", postType: "mate_reply", text: "ホウ先生ッ！目次チェック、仕事の資料にも使えるッ！まず全体を見るッ！" },
  { id: "thread-piyori-mike", mateId: "piyori", replyToMateId: "nekosenpai", category: "writing", trigger: "app_open", postType: "mate_reply", text: "ミケ先輩の白紙より強い、好きぴよ。タイトルだけでも羽が置けるぴよ〜。" },
  { id: "thread-mike-piyori", mateId: "nekosenpai", replyToMateId: "piyori", category: "creative", trigger: "app_open", postType: "mate_reply", text: "ピヨリ、失敗案を捨てないのはえらいわ。あとで使うから名前だけ付けときなさい。" },
  { id: "thread-aza-usamaru", mateId: "azamaru", replyToMateId: "usamaru", trigger: "app_open", postType: "mate_reply", text: "うさ丸、入口を小さくするのえらいまる。押せたら水も飲むまる。" },
  { id: "thread-usamaru-kame", mateId: "usamaru", replyToMateId: "kamekichi", trigger: "app_open", postType: "mate_reply", text: "かめ吉のゆっくり案内、安心するね！うさ丸もひとつずつ進むよ！" },
  { id: "thread-kame-aza", mateId: "kamekichi", replyToMateId: "azamaru", category: "care", trigger: "app_open", postType: "mate_reply", text: "あざまるの休む作戦、ええねぇ。休憩も予定に入れたら迷わんで済むねぇ。" },

  { id: "start-wani-1", mateId: "waniyan", category: "organize", trigger: "task_start", postType: "mate_reply", text: "全部やらんでええ。床のもん1個拾ったら勝ちや。" },
  { id: "start-wani-2", mateId: "waniyan", category: "organize", trigger: "task_start", postType: "mate_reply", text: "10秒だけいこか。ピカピカはまた今度でええ。" },
  { id: "start-wani-3", mateId: "waniyan", category: "organize", trigger: "task_start", postType: "mate_reply", text: "見える場所からや。引き出しの奥は今日は知らん顔でええ。" },
  { id: "start-wani-4", mateId: "waniyan", category: "organize", trigger: "task_start", postType: "mate_reply", text: "まず視界に入った1個だけや。部屋全体と戦わんでええ。" },
  { id: "start-wani-5", mateId: "waniyan", category: "organize", trigger: "task_start", postType: "mate_reply", text: "片付けは大掃除ちゃう。生活の通路をちょっと開けるだけや。" },
  { id: "start-kumaru-1", mateId: "kumaru", category: "housework", trigger: "task_start", postType: "mate_reply", text: "お皿1枚だけ洗おっかぁ。全部じゃなくていいよぉ。" },
  { id: "start-kumaru-2", mateId: "kumaru", category: "housework", trigger: "task_start", postType: "mate_reply", text: "洗濯、回すだけでも未来の自分が助かるよぉ〜。" },
  { id: "start-kumaru-3", mateId: "kumaru", category: "housework", trigger: "task_start", postType: "mate_reply", text: "買い物メモは1個だけでもいいよぉ。思い出した分だけで十分だよぉ。" },
  { id: "start-kumaru-4", mateId: "kumaru", category: "housework", trigger: "task_start", postType: "mate_reply", text: "暮らしは小さく回せばいいよぉ。まず手前のひとつからねぇ。" },
  { id: "start-kumaru-5", mateId: "kumaru", category: "housework", trigger: "task_start", postType: "mate_reply", text: "未来の自分に、ちょっとだけ差し入れしよっかぁ。" },
  { id: "start-shiba-1", mateId: "shibatarou", category: "work", trigger: "task_start", postType: "mate_reply", text: "期限だけ確認しよ！やるかどうかはそのあとでいいッ！" },
  { id: "start-shiba-2", mateId: "shibatarou", category: "work", trigger: "task_start", postType: "mate_reply", text: "5分だけ仕事モード入ろッ！5分後に逃げてもセーフッ！" },
  { id: "start-shiba-3", mateId: "shibatarou", category: "work", trigger: "task_start", postType: "mate_reply", text: "通知欄を開くだけでも現実対応ッ！返事はあとでいいッ！" },
  { id: "start-shiba-4", mateId: "shibatarou", category: "work", trigger: "task_start", postType: "mate_reply", text: "まずタイトルだけ見るッ！正体がわかれば、ちょっと弱くなるッ！" },
  { id: "start-shiba-5", mateId: "shibatarou", category: "work", trigger: "task_start", postType: "mate_reply", text: "重いタスクは分解ッ！開く、読む、1行返す。今日はどれかでOKッ！" },
  { id: "start-hou-1", mateId: "fukurou", category: "learning", trigger: "task_start", postType: "mate_reply", text: "今日は1ページだけ読みましょう。少しでも、知識は残りますよ。" },
  { id: "start-hou-2", mateId: "fukurou", category: "learning", trigger: "task_start", postType: "mate_reply", text: "コードは1行眺めるだけでも学ぶことです。焦らなくていいですよ。" },
  { id: "start-hou-3", mateId: "fukurou", category: "learning", trigger: "task_start", postType: "mate_reply", text: "理解できない場所に印をつけるだけでも、次の学びの入口になります。" },
  { id: "start-hou-4", mateId: "fukurou", category: "learning", trigger: "task_start", postType: "mate_reply", text: "今日は全体像を見るだけでも構いません。目次は良い地図になりますよ。" },
  { id: "start-hou-5", mateId: "fukurou", category: "learning", trigger: "task_start", postType: "mate_reply", text: "わからないところを見つけたら、それは失敗ではなく発見です。" },
  { id: "start-mike-1", mateId: "nekosenpai", category: "writing", trigger: "task_start", postType: "mate_reply", text: "いきなり名文を書こうとするから止まるのよ。下書きでいいの。" },
  { id: "start-mike-2", mateId: "nekosenpai", category: "writing", trigger: "task_start", postType: "mate_reply", text: "その違和感、メモしときなさい。あとで記事になるかもね。" },
  { id: "start-mike-3", mateId: "nekosenpai", category: "writing", trigger: "task_start", postType: "mate_reply", text: "一文が変でもいいの。変だと気づける材料ができたってことだから。" },
  { id: "start-mike-4", mateId: "nekosenpai", category: "writing", trigger: "task_start", postType: "mate_reply", text: "まず雑に置きなさい。直すのは、そこに何かある人だけができるの。" },
  { id: "start-mike-5", mateId: "nekosenpai", category: "writing", trigger: "task_start", postType: "mate_reply", text: "タイトルだけでも書きなさい。白紙より、仮の名前がある方が強いわ。" },
  { id: "start-piyori-1", mateId: "piyori", category: "creative", trigger: "task_start", postType: "mate_reply", text: "完成までいけなくても、素材をチェックだけでいいぴよ〜。" },
  { id: "start-piyori-2", mateId: "piyori", category: "creative", trigger: "task_start", postType: "mate_reply", text: "今日は1パーツだけ触るぴよ。作品は小さい羽からできるぴよ〜。" },
  { id: "start-piyori-3", mateId: "piyori", category: "creative", trigger: "task_start", postType: "mate_reply", text: "開くだけ、鳴らすだけ、置くだけ。制作の入口は小さくていいぴよ。" },
  { id: "start-piyori-4", mateId: "piyori", category: "creative", trigger: "task_start", postType: "mate_reply", text: "完成の顔をしなくていいぴよ。今日は試すだけで制作ぴよ〜。" },
  { id: "start-piyori-5", mateId: "piyori", category: "creative", trigger: "task_start", postType: "mate_reply", text: "素材フォルダを開いたら、もう入口に立ってるぴよ。" },
  { id: "start-aza-1", mateId: "azamaru", category: "care", trigger: "task_start", postType: "mate_reply", text: "水飲んだ？えらいまる。生命維持、できてるまる。" },
  { id: "start-aza-2", mateId: "azamaru", category: "care", trigger: "task_start", postType: "mate_reply", text: "おふろ入れたら勝ちまる。今日は回復クエストでいいまる。" },
  { id: "start-aza-3", mateId: "azamaru", category: "care", trigger: "task_start", postType: "mate_reply", text: "休憩を予定に入れるの、かなり上手な作戦まる。" },
  { id: "start-aza-4", mateId: "azamaru", category: "care", trigger: "task_start", postType: "mate_reply", text: "肩を一回まわすだけでも、からだに戻ってきた合図になるまる。" },
  { id: "start-aza-5", mateId: "azamaru", category: "care", trigger: "task_start", postType: "mate_reply", text: "今日は整えるより戻す日でもいいまる。息をひとつ入れるまる。" },

  { id: "start-usamaru-2", mateId: "usamaru", trigger: "task_start", postType: "mate_reply", text: "始めるボタン押せた！ここからは小さく刻めばOKだよ！" },
  { id: "start-kame-2", mateId: "kamekichi", trigger: "task_start", postType: "mate_reply", text: "まず始まったねぇ。途中で止まっても、ここに戻ってくればええよぉ。" },
  { id: "start-aza-general", mateId: "azamaru", trigger: "task_start", postType: "mate_reply", text: "始める前に息をひとつ入れるまる。力みすぎんでいいまる。" },
  { id: "start-hou-general", mateId: "fukurou", trigger: "task_start", postType: "mate_reply", text: "開始できた時点で、次の判断材料が生まれました。落ち着いていきましょう。" },

  { id: "start-usamaru", mateId: "usamaru", trigger: "task_start", postType: "mate_reply", text: "開始できた！まず押せたのがえらい！", minAffinity: 4 },
  { id: "start-kame", mateId: "kamekichi", trigger: "task_start", postType: "mate_reply", text: "短い時間でええよぉ。戻れる場所があるのは安心やねぇ。", minAffinity: 4 },

  { id: "progress-wani", mateId: "waniyan", category: "organize", trigger: "progress", postType: "mate_reply", text: "まだ続いてるやん。ええ粘りしてるで。" },
  { id: "progress-wani-2", mateId: "waniyan", category: "organize", trigger: "progress", postType: "mate_reply", text: "そこまで触れたら十分や。次は戻す場所を1個だけ決めよか。" },
  { id: "progress-wani-3", mateId: "waniyan", category: "organize", trigger: "progress", postType: "mate_reply", text: "完璧に寄せんでええ。さっきより通路が見えたら勝ちや。" },
  { id: "progress-kumaru", mateId: "kumaru", category: "housework", trigger: "progress", postType: "mate_reply", text: "途中まででも生活はちゃんと回ってるよぉ〜。" },
  { id: "progress-kumaru-2", mateId: "kumaru", category: "housework", trigger: "progress", postType: "mate_reply", text: "いま動いた分、あとで少し助かるよぉ。無理に増やさなくていいよぉ。" },
  { id: "progress-kumaru-3", mateId: "kumaru", category: "housework", trigger: "progress", postType: "mate_reply", text: "暮らしの途中って、ちゃんと暮らしだよぉ。ここまでで十分あたたかいよぉ。" },
  { id: "progress-shiba", mateId: "shibatarou", category: "work", trigger: "progress", postType: "mate_reply", text: "ここまで見られたなら十分ッ！次は1個だけでOKッ！" },
  { id: "progress-shiba-2", mateId: "shibatarou", category: "work", trigger: "progress", postType: "mate_reply", text: "現実対応、接続維持ッ！ここで次の一手だけ確認ッ！" },
  { id: "progress-shiba-3", mateId: "shibatarou", category: "work", trigger: "progress", postType: "mate_reply", text: "途中で重くなったら、見るだけに戻してOKッ！撤退じゃなくて調整ッ！" },
  { id: "progress-hou", mateId: "fukurou", category: "learning", trigger: "progress", postType: "mate_reply", text: "ここで一度、次の一動作だけに視点を戻しましょう。" },
  { id: "progress-hou-2", mateId: "fukurou", category: "learning", trigger: "progress", postType: "mate_reply", text: "理解が追いつかない時は、わからない場所に名前をつけるだけで大丈夫です。" },
  { id: "progress-hou-3", mateId: "fukurou", category: "learning", trigger: "progress", postType: "mate_reply", text: "いま触れている時間そのものが、次に思い出すための準備になりますよ。" },
  { id: "progress-mike", mateId: "nekosenpai", category: "writing", trigger: "progress", postType: "mate_reply", text: "消さずに残してるだけでも、まあ悪くないわね。" },
  { id: "progress-mike-2", mateId: "nekosenpai", category: "writing", trigger: "progress", postType: "mate_reply", text: "詰まったら、詰まったって書きなさい。それも本文の入口になるわ。" },
  { id: "progress-mike-3", mateId: "nekosenpai", category: "writing", trigger: "progress", postType: "mate_reply", text: "整ってなくていいの。いまは素材を出してる段階でしょ。" },
  { id: "progress-piyori", mateId: "piyori", category: "creative", trigger: "progress", postType: "mate_reply", text: "試してる途中がいちばん大事ぴよ〜。" },
  { id: "progress-piyori-2", mateId: "piyori", category: "creative", trigger: "progress", postType: "mate_reply", text: "途中の形、ちゃんと見えてきてるぴよ。完成前の羽も作品ぴよ〜。" },
  { id: "progress-piyori-3", mateId: "piyori", category: "creative", trigger: "progress", postType: "mate_reply", text: "変な案が出ても大丈夫ぴよ。そこから次の案が飛ぶぴよ〜。" },
  { id: "progress-aza", mateId: "azamaru", category: "care", trigger: "progress", postType: "mate_reply", text: "続いてるだけでえらいまる。力は抜くまる。" },
  { id: "progress-aza-2", mateId: "azamaru", category: "care", trigger: "progress", postType: "mate_reply", text: "呼吸浅くなってたら、いったん吐くまる。続きはそのあとでいいまる。" },
  { id: "progress-aza-3", mateId: "azamaru", category: "care", trigger: "progress", postType: "mate_reply", text: "からだの声を聞きながらでいいまる。がんばりすぎは調整するまる。" },
  { id: "progress-usamaru", mateId: "usamaru", trigger: "progress", postType: "mate_reply", text: "まだ続いてる！すごいよ、もう途中経過ができてるよ！" },
  { id: "progress-kame", mateId: "kamekichi", trigger: "progress", postType: "mate_reply", text: "ええ調子やねぇ。次のひと動作だけ見れば十分やよぉ。" },
  { id: "progress-kumaru-general", mateId: "kumaru", trigger: "progress", postType: "mate_reply", text: "途中まででも、あとで助かるぶんはちゃんと増えてるよぉ〜。" },
  { id: "progress-shiba-general", mateId: "shibatarou", trigger: "progress", postType: "mate_reply", text: "中間地点確認ッ！ここまで来た事実を採用するッ！" },

  { id: "complete-wani", mateId: "waniyan", category: "organize", trigger: "complete", postType: "mate_reply", text: "ええやん。今の整え、ちゃんと自分の手柄にしときや。" },
  { id: "complete-wani-2", mateId: "waniyan", category: "organize", trigger: "complete", postType: "mate_reply", text: "見える場所が少し戻ったな。生活の足場、ちゃんと増えたで。" },
  { id: "complete-wani-3", mateId: "waniyan", category: "organize", trigger: "complete", postType: "mate_reply", text: "置き場所がひとつ決まったら、次の迷いが減るんや。ええ整備やで。" },
  { id: "complete-kumaru", mateId: "kumaru", category: "housework", trigger: "complete", postType: "mate_reply", text: "できたねぇ。暮らしが少し回ったよぉ〜。" },
  { id: "complete-kumaru-2", mateId: "kumaru", category: "housework", trigger: "complete", postType: "mate_reply", text: "ひとつ済んだねぇ。未来の自分に、ちゃんと届くよぉ。" },
  { id: "complete-kumaru-3", mateId: "kumaru", category: "housework", trigger: "complete", postType: "mate_reply", text: "暮らしの歯車、今日はちゃんと一回まわったねぇ。これで十分だよぉ。" },
  { id: "complete-shiba", mateId: "shibatarou", category: "work", trigger: "complete", postType: "mate_reply", text: "できたッ！今日の現実対応、ちゃんと前に進んだッ！" },
  { id: "complete-shiba-2", mateId: "shibatarou", category: "work", trigger: "complete", postType: "mate_reply", text: "現実対応クリアッ！小さくても、先延ばしを削った事実は強いッ！" },
  { id: "complete-shiba-3", mateId: "shibatarou", category: "work", trigger: "complete", postType: "mate_reply", text: "完了報告ッ！次に開く時の圧が、いま少し下がったッ！" },
  { id: "complete-hou", mateId: "fukurou", category: "learning", trigger: "complete", postType: "mate_reply", text: "完了です。学びに触れた記録として、十分に良い一歩ですよ。" },
  { id: "complete-hou-2", mateId: "fukurou", category: "learning", trigger: "complete", postType: "mate_reply", text: "今日触れた知識は、また出会った時に少し親しみやすくなりますよ。" },
  { id: "complete-hou-3", mateId: "fukurou", category: "learning", trigger: "complete", postType: "mate_reply", text: "理解を急がず終えられましたね。学びを続けるには、その区切り方が大切です。" },
  { id: "complete-mike", mateId: "nekosenpai", category: "writing", trigger: "complete", postType: "mate_reply", text: "書けたじゃない。雑でも、置いた言葉はちゃんと残るわ。" },
  { id: "complete-mike-2", mateId: "nekosenpai", category: "writing", trigger: "complete", postType: "mate_reply", text: "白紙じゃなくなった。それだけで、明日の自分はだいぶ助かるわ。" },
  { id: "complete-mike-3", mateId: "nekosenpai", category: "writing", trigger: "complete", postType: "mate_reply", text: "最後まで置いたなら上出来よ。直す権利は、書いた人にだけあるんだから。" },
  { id: "complete-piyori", mateId: "piyori", category: "creative", trigger: "complete", postType: "mate_reply", text: "できたぴよ〜。小さい試作もちゃんとつくった証ぴよ。" },
  { id: "complete-piyori-2", mateId: "piyori", category: "creative", trigger: "complete", postType: "mate_reply", text: "羽が1枚増えたぴよ。完成じゃなくても、ちゃんと制作ぴよ〜。" },
  { id: "complete-piyori-3", mateId: "piyori", category: "creative", trigger: "complete", postType: "mate_reply", text: "保存できたなら今日は勝ちぴよ。次の自分が続きを見つけやすいぴよ〜。" },
  { id: "complete-aza", mateId: "azamaru", category: "care", trigger: "complete", postType: "mate_reply", text: "できたまる。今日は体と心がちょっとととのったまる。" },
  { id: "complete-aza-2", mateId: "azamaru", category: "care", trigger: "complete", postType: "mate_reply", text: "戻す時間を作れたまる。からだ、ちゃんと助かってるまる。" },
  { id: "complete-aza-3", mateId: "azamaru", category: "care", trigger: "complete", postType: "mate_reply", text: "自分の面倒を見た記録まる。地味だけど、かなり大事な完了まる。" },
  { id: "complete-usamaru-general", mateId: "usamaru", trigger: "complete", postType: "mate_reply", text: "できた記録、残ったね！今日の自分にちゃんと見える形になったよ！" },
  { id: "complete-kame-general", mateId: "kamekichi", trigger: "complete", postType: "mate_reply", text: "ええねぇ。急がんでも、こうしてひとつ残るのは大きいんやでぇ。" },

  { id: "partial-wani", mateId: "waniyan", category: "organize", trigger: "partial", postType: "mate_reply", text: "少し片付いたならええやん。ゼロから動かしたんは事実や。" },
  { id: "partial-wani-2", mateId: "waniyan", category: "organize", trigger: "partial", postType: "mate_reply", text: "途中まででええ。次に触る場所が見えたなら、かなり進んでるで。" },
  { id: "partial-wani-3", mateId: "waniyan", category: "organize", trigger: "partial", postType: "mate_reply", text: "全部は動かんでも、手前がちょっと変わったら空気も変わるんや。" },
  { id: "partial-kumaru", mateId: "kumaru", category: "housework", trigger: "partial", postType: "mate_reply", text: "ちょっとできたなら十分だよぉ。また続きからでいいよぉ〜。" },
  { id: "partial-kumaru-2", mateId: "kumaru", category: "housework", trigger: "partial", postType: "mate_reply", text: "暮らしは途中でも回るよぉ。今日はここまででも、ちゃんと助かるよぉ。" },
  { id: "partial-kumaru-3", mateId: "kumaru", category: "housework", trigger: "partial", postType: "mate_reply", text: "半分でも家は少し軽くなるよぉ。残りはまた元気な時でいいねぇ。" },
  { id: "partial-shiba", mateId: "shibatarou", category: "work", trigger: "partial", postType: "mate_reply", text: "少し見たならOKッ！次に戻る場所ができたッ！" },
  { id: "partial-shiba-2", mateId: "shibatarou", category: "work", trigger: "partial", postType: "mate_reply", text: "途中まで確認ッ！未完了じゃなくて、次の入口を作ったッ！" },
  { id: "partial-shiba-3", mateId: "shibatarou", category: "work", trigger: "partial", postType: "mate_reply", text: "少しでも正体を見たッ！未知のまま置かないだけで強いッ！" },
  { id: "partial-hou", mateId: "fukurou", category: "learning", trigger: "partial", postType: "mate_reply", text: "残りは次回の開始点です。今日はわかった部分だけ見ましょう。" },
  { id: "partial-hou-2", mateId: "fukurou", category: "learning", trigger: "partial", postType: "mate_reply", text: "半分の理解でも価値があります。輪郭が見えたなら前進ですよ。" },
  { id: "partial-hou-3", mateId: "fukurou", category: "learning", trigger: "partial", postType: "mate_reply", text: "疑問が残ったなら良い途中です。次に調べる場所ができました。" },
  { id: "partial-mike", mateId: "nekosenpai", category: "writing", trigger: "partial", postType: "mate_reply", text: "全部じゃなくてもいいでしょ。途中まででも書いた側よ。" },
  { id: "partial-mike-2", mateId: "nekosenpai", category: "writing", trigger: "partial", postType: "mate_reply", text: "途中の文、消さないで置いときなさい。あとで拾えるから。" },
  { id: "partial-mike-3", mateId: "nekosenpai", category: "writing", trigger: "partial", postType: "mate_reply", text: "切れ端でも残しておきなさい。あとで一番使えるの、そういう部分だったりするわ。" },
  { id: "partial-piyori", mateId: "piyori", category: "creative", trigger: "partial", postType: "mate_reply", text: "途中でも素材になるぴよ〜。消さなくていいぴよ。" },
  { id: "partial-piyori-2", mateId: "piyori", category: "creative", trigger: "partial", postType: "mate_reply", text: "ちょっと触った形跡が残ったぴよ。次の羽ばたき台ぴよ〜。" },
  { id: "partial-piyori-3", mateId: "piyori", category: "creative", trigger: "partial", postType: "mate_reply", text: "試した色や形は、途中でもちゃんと候補ぴよ。保存しておくぴよ〜。" },
  { id: "partial-aza", mateId: "azamaru", category: "care", trigger: "partial", postType: "mate_reply", text: "少しできたまる。体にはそれで十分な日もあるまる。" },
  { id: "partial-aza-2", mateId: "azamaru", category: "care", trigger: "partial", postType: "mate_reply", text: "少し戻せたまる。足りない分は、休む時間が引き受けるまる。" },
  { id: "partial-aza-3", mateId: "azamaru", category: "care", trigger: "partial", postType: "mate_reply", text: "途中まで自分を見られたまる。続きより、まずその分を採用するまる。" },
  { id: "partial-usamaru-general", mateId: "usamaru", trigger: "partial", postType: "mate_reply", text: "少しできた、ちゃんと記録だよ！次の自分がここから続けられるね。" },
  { id: "partial-kame-general", mateId: "kamekichi", trigger: "partial", postType: "mate_reply", text: "途中まで来たんやねぇ。置いたところが見えたら、また戻りやすいでぇ。" },

  { id: "interrupted-wani", mateId: "waniyan", category: "organize", trigger: "interrupted", postType: "mate_reply", text: "中断も作業のうちや。触った場所だけ覚えて、いったん置いとこ。" },
  { id: "interrupted-wani-2", mateId: "waniyan", category: "organize", trigger: "interrupted", postType: "mate_reply", text: "途中で止めたなら、それ以上散らかさんかっただけでも勝ちや。" },
  { id: "interrupted-wani-3", mateId: "waniyan", category: "organize", trigger: "interrupted", postType: "mate_reply", text: "今日はここで止めとこ。通路をふさがん判断も、ちゃんと整える側や。" },
  { id: "interrupted-kumaru", mateId: "kumaru", category: "housework", trigger: "interrupted", postType: "mate_reply", text: "止まっても大丈夫だよぉ。暮らしはまた戻れるよぉ〜。" },
  { id: "interrupted-kumaru-2", mateId: "kumaru", category: "housework", trigger: "interrupted", postType: "mate_reply", text: "今日はここまでだねぇ。暮らしは逃げないから、またゆっくりでいいよぉ。" },
  { id: "interrupted-kumaru-3", mateId: "kumaru", category: "housework", trigger: "interrupted", postType: "mate_reply", text: "家事は途中で置いても暮らしの中に残るよぉ。戻れた時に続きを拾おうねぇ。" },
  { id: "interrupted-shiba", mateId: "shibatarou", category: "work", trigger: "interrupted", postType: "mate_reply", text: "中断でも記録は残ったッ！また見ればOKッ！" },
  { id: "interrupted-shiba-2", mateId: "shibatarou", category: "work", trigger: "interrupted", postType: "mate_reply", text: "撤退判断、記録完了ッ！次はここから再突入できるッ！" },
  { id: "interrupted-shiba-3", mateId: "shibatarou", category: "work", trigger: "interrupted", postType: "mate_reply", text: "止めた地点を記録ッ！次の再開ポイントを確保したッ！" },
  { id: "interrupted-hou", mateId: "fukurou", category: "learning", trigger: "interrupted", postType: "mate_reply", text: "止めたことも、状況を見た結果です。次は印をつけた場所からで大丈夫ですよ。" },
  { id: "interrupted-hou-2", mateId: "fukurou", category: "learning", trigger: "interrupted", postType: "mate_reply", text: "学びは中断しても失われません。次に開く場所がわかれば十分です。" },
  { id: "interrupted-hou-3", mateId: "fukurou", category: "learning", trigger: "interrupted", postType: "mate_reply", text: "集中が切れたなら閉じましょう。学習は、戻れる余白も含めて設計です。" },
  { id: "interrupted-mike", mateId: "nekosenpai", category: "writing", trigger: "interrupted", postType: "mate_reply", text: "途中で止まっても、言葉の欠片は残るわ。捨てずに置いときなさい。" },
  { id: "interrupted-mike-2", mateId: "nekosenpai", category: "writing", trigger: "interrupted", postType: "mate_reply", text: "中断したならメモだけ残しなさい。未来のあなたが文句言いながら拾うわ。" },
  { id: "interrupted-mike-3", mateId: "nekosenpai", category: "writing", trigger: "interrupted", postType: "mate_reply", text: "今日は閉じていいわ。開いた時に困らないよう、一言だけ残せたら十分よ。" },
  { id: "interrupted-piyori", mateId: "piyori", category: "creative", trigger: "interrupted", postType: "mate_reply", text: "中断しても試した事実は残るぴよ〜。素材は逃げないぴよ。" },
  { id: "interrupted-piyori-2", mateId: "piyori", category: "creative", trigger: "interrupted", postType: "mate_reply", text: "今日は羽をたたむぴよ。次に開いた時、続きから飛べるぴよ〜。" },
  { id: "interrupted-piyori-3", mateId: "piyori", category: "creative", trigger: "interrupted", postType: "mate_reply", text: "閉じても試作は消えないぴよ。次に見る自分への目印になるぴよ〜。" },
  { id: "interrupted-aza", mateId: "azamaru", category: "care", trigger: "interrupted", postType: "mate_reply", text: "止まったなら休むまる。また戻れたらそれでいいまる。" },
  { id: "interrupted-aza-2", mateId: "azamaru", category: "care", trigger: "interrupted", postType: "mate_reply", text: "中断できたのも、自分を守る判断まる。水だけ飲むまる。" },
  { id: "interrupted-aza-3", mateId: "azamaru", category: "care", trigger: "interrupted", postType: "mate_reply", text: "無理の手前で止まれたなら、それはかなり上手なケアまる。" },
  { id: "interrupted-usamaru-general", mateId: "usamaru", trigger: "interrupted", postType: "mate_reply", text: "止める判断も記録にできたね。戻る場所ができたの、かなり大事だよ。" },
  { id: "interrupted-kame-general", mateId: "kamekichi", trigger: "interrupted", postType: "mate_reply", text: "いったん置いたんやねぇ。置き場所がわかってたら、続きはまた拾えるでぇ。" },
];
