import type {
  MateComment,
  MateId,
  MateProfile,
  QuestTemplate,
  TaskCategory,
  TaskResult,
  TicketDefinition,
} from "./types";

export const mates: Record<MateId, MateProfile> = {
  waniyan: {
    id: "waniyan",
    name: "ワニやん",
    emoji: "🐊",
    imageSrc: "/mates/waniyan.png",
    role: "整える担当",
    note: "全部やらんでええ。1個やったら勝ちや。",
    accent: "#69a77d",
    profileId: "@waniyan_totonoeru",
    bio: "部屋の平和は、床のもの1個からや。掃除・片付け・ゴミまとめ担当。全部やらんでええ、1か所だけで勝ちや🐊",
    pinnedPost: "完璧に片付けようとするから動けんねん。\n今日は机の上を3つだけかたそ。\nそれで生活、ちょっと勝ちや。",
    profileTags: ["掃除", "片付け", "1か所だけ"],
  },
  kumaru: {
    id: "kumaru",
    name: "くまる",
    emoji: "🐻",
    imageSrc: "/mates/kumaru.png",
    role: "暮らす担当",
    note: "暮らしをゆっくり回してくれる。",
    accent: "#b88958",
    profileId: "@kumaru_kurasu",
    bio: "洗濯、洗い物、料理、買い物。暮らしをゆっくり回す係だよぉ〜。未来の自分がちょっと助かる家事を、一緒にやろうねぇ🐻",
    pinnedPost: "洗濯を回すだけでも、未来の自分が助かるよぉ〜。\nお皿1枚でも、買い物メモ1つでも、ちゃんと暮らしは進んでるよぉ。",
    profileTags: ["洗濯", "洗い物", "買い物メモ"],
  },
  shibatarou: {
    id: "shibatarou",
    name: "しばたろう",
    emoji: "🐕",
    imageSrc: "/mates/shibatarou.png",
    role: "働く担当",
    note: "現実を一緒に1個だけ見に行く相棒。",
    accent: "#e49a3f",
    profileId: "@shibataro_work",
    bio: "仕事・連絡・手続き・お金の確認担当ッ！まず1通、まず1分、まず見るだけでOKッ！一緒に現実を見に行く柴犬です🐕",
    pinnedPost: "期限だけ確認しよッ！\nやるかどうかは、そのあとでいいッ！\nまず見るだけでも、先延ばしに一撃入ってるッ！",
    profileTags: ["仕事", "連絡", "期限確認"],
  },
  fukurou: {
    id: "fukurou",
    name: "ホウ先生",
    emoji: "🦉",
    imageSrc: "/mates/fukurou.png",
    role: "学ぶ担当",
    note: "わからない場所を見つけるのも前進です。",
    accent: "#7f8fb0",
    profileId: "@hou_sensei_learn",
    bio: "読書、勉強、コード学習、調べものを見守っています。1ページでも、1行でも、理解できない場所を見つけるだけでも前進ですよ🦉",
    pinnedPost: "今日は1ページだけ読みましょう。\n少しでも、知識は残りますよ。\n焦らなくて大丈夫です。学びは静かに積もります。",
    profileTags: ["読書", "勉強", "コード学習"],
  },
  nekosenpai: {
    id: "nekosenpai",
    name: "ミケ先輩",
    emoji: "🐈",
    imageSrc: "/mates/nekosenpai.png",
    role: "書く担当",
    note: "下書きでいいの。まず1行置きなさい。",
    accent: "#d9939b",
    profileId: "@mike_senpai_write",
    bio: "note・日記・SNS・台本・メモ担当。いきなり名文を書こうとするから止まるのよ。1行書いたら、まあ今日は認めてあげるわ🐈",
    pinnedPost: "下書きでいいの。\nタイトルだけでもいいの。\nその違和感、メモしときなさい。あとで記事になるかもね。",
    profileTags: ["note", "日記", "下書き"],
  },
  piyori: {
    id: "piyori",
    name: "ピヨリ",
    emoji: "🐦",
    imageSrc: "/mates/piyori.png",
    role: "つくる担当",
    note: "完成より、まず触ってみるぴよ〜。",
    accent: "#e7bf4f",
    profileId: "@piyori_create",
    bio: "Vlog、写真、動画、アプリ、デザイン、音楽、創作担当ぴよ〜。完成しなくても、素材チェックだけで制作は始まってるぴよ🐦",
    pinnedPost: "完成までいけなくてもいいぴよ〜。\n素材を1個見るだけ、1パーツ触るだけ、アイデアを置くだけ。\n小さい羽から作品はできるぴよ。",
    profileTags: ["Vlog", "デザイン", "試作"],
  },
  azamaru: {
    id: "azamaru",
    name: "あざまる",
    emoji: "🦭",
    imageSrc: "/mates/azamaru.png",
    role: "ととのう担当",
    note: "休むのもクエストまる。",
    accent: "#95b8c8",
    profileId: "@azamaru_totono",
    bio: "散歩、運動、筋トレ、おふろ、休憩、睡眠準備、水分担当まる。少し動くのも、ちゃんと休むのも、どっちもえらいまる🦭",
    pinnedPost: "水飲んだ？えらいまる。\n5分歩いた？えらいまる。\n何もしないで休んだ？それも体を戻してるまる。",
    profileTags: ["散歩", "休憩", "睡眠準備"],
  },
  usamaru: {
    id: "usamaru",
    name: "うさ丸",
    emoji: "🐰",
    imageSrc: "/mates/usamaru.png",
    role: "チュートリアル担当",
    note: "はじめての操作を明るく案内する。",
    accent: "#e7ad62",
    profileId: "@usamaru_start",
    bio: "はじめての一歩を案内する係だよ！迷ったら3分、押せたら勝ち。わからないところは一緒に見ていこう！🐰",
    pinnedPost: "最初はぜんぶ覚えなくてOK！\n3分だけ、1個だけ、押してみるだけ。\n始めた瞬間から、もう進んでるよ！",
    profileTags: ["はじめる", "3分", "案内"],
  },
  kamekichi: {
    id: "kamekichi",
    name: "かめ吉",
    emoji: "🐢",
    imageSrc: "/mates/kamekichi.png",
    role: "ページ案内担当",
    note: "クエスト、チケット、達成画面をゆっくり案内する。",
    accent: "#7eb6b2",
    profileId: "@kamekichi_guide",
    bio: "クエスト、チケット、達成画面をゆっくり案内する担当やねぇ。急がんでええよぉ。ひとつずつ見ていこか🐢",
    pinnedPost: "画面が多く見える日は、ひとつだけ見たらええよぉ。\nクエストもチケットも、生活を助ける道具やからねぇ。",
    profileTags: ["クエスト", "チケット", "達成"],
  },
};

export const categories: {
  id: TaskCategory;
  label: string;
  conceptLabel: string;
  subcategories: string[];
  summary: string;
  hoverDescription: string;
  questExamples: string[];
}[] = [
  {
    id: "organize",
    label: "整える",
    conceptLabel: "整える",
    subcategories: ["掃除", "片付け", "ゴミ", "玄関", "机まわり", "冷蔵庫整理", "収納", "空間リセット"],
    summary: "部屋や物のノイズを少し減らす",
    hoverDescription: "掃除・片付け・ゴミ・収納など、空間を少し軽くするクエスト。全部やらなくてOK。1か所だけ整えたら勝ち。",
    questExamples: ["洗面台を10秒だけ拭く", "机の上のものを3つ戻す", "ゴミを1袋まとめる"],
  },
  {
    id: "housework",
    label: "暮らす",
    conceptLabel: "暮らす",
    subcategories: ["洗い物", "洗濯", "料理", "買い物", "日用品", "食材管理", "ペット用品", "家の補充"],
    summary: "暮らしを回す",
    hoverDescription: "洗濯・洗い物・料理・買い物・日用品補充など、暮らしを回すクエスト。未来の自分がちょっと助かる作業。",
    questExamples: ["洗濯を回す", "お皿を1枚だけ洗う", "猫の水皿を洗う"],
  },
  {
    id: "work",
    label: "働く",
    conceptLabel: "働く",
    subcategories: ["仕事", "連絡", "返信", "確認", "手続き", "お金", "書類", "期限"],
    summary: "現実対応を1つ見る",
    hoverDescription: "仕事・連絡・返信・手続き・お金・期限確認など、現実対応のクエスト。まず見るだけでもOK。",
    questExamples: ["メールを1通だけ見る", "期限だけ確認する", "5分だけ作業する"],
  },
  {
    id: "learning",
    label: "学ぶ",
    conceptLabel: "学ぶ",
    subcategories: ["勉強", "読書", "コード学習", "調べもの", "資格", "技術メモ", "復習", "理解整理"],
    summary: "知識を少し進める",
    hoverDescription: "勉強・読書・コード学習・調べものなど、知識を少し進めるクエスト。理解できない場所を見つけるだけでも前進。",
    questExamples: ["本を1ページ読む", "用語を1つ調べる", "コードを1行眺める"],
  },
  {
    id: "writing",
    label: "書く",
    conceptLabel: "書く",
    subcategories: ["note", "日記", "SNS", "X投稿", "stand.fm台本", "メモ", "考えの整理", "下書き"],
    summary: "考えを言葉にする",
    hoverDescription: "言葉にする作業。note、日記、SNS投稿、台本、メモ、考えの整理など。名文じゃなくてOK。下書きで十分。",
    questExamples: ["1行だけ書く", "タイトルだけ置く", "X投稿の下書きを作る"],
  },
  {
    id: "creative",
    label: "つくる",
    conceptLabel: "つくる",
    subcategories: ["Vlog", "写真", "動画", "アプリ開発", "デザイン", "音楽", "創作", "プロダクト"],
    summary: "何かを作る",
    hoverDescription: "Vlog・写真・動画・アプリ・デザイン・音楽など、何かを作るクエスト。完成しなくてOK。少し触るだけでもつくる時間。",
    questExamples: ["Vlog素材を1本だけ見る", "写真を5枚だけ整理する", "アイデアを1つ置く"],
  },
  {
    id: "care",
    label: "ととのう",
    conceptLabel: "ととのう",
    subcategories: ["散歩", "運動", "筋トレ", "ストレッチ", "おふろ", "休憩", "睡眠準備", "水分"],
    summary: "体と心を戻す",
    hoverDescription: "散歩・運動・筋トレ・ストレッチ・おふろ・睡眠準備など、体と心を回復・維持するクエスト。少し動くのも、ちゃんと休むのもここ。",
    questExamples: ["水を飲む", "スクワットを3回する", "目を閉じて1分休む"],
  },
];

export const durations = [3, 5, 15, 25];

export const resultLabels: Record<TaskResult, string> = {
  complete: "できた",
  partial: "少しできた",
  interrupted: "中断した",
  failed: "無理だった",
};

export const mateQuestTemplates: QuestTemplate[] = [
  { id: "organize-sink", title: "洗面台の水滴を拭く", minutes: 2, category: "organize", source: "mate", suggestedBy: "waniyan", enabled: true },
  { id: "organize-desk-three", title: "机の上のものを3つ戻す", minutes: 1, category: "organize", source: "mate", suggestedBy: "waniyan", enabled: true },
  { id: "organize-floor-one", title: "床のものを1個拾う", minutes: 1, category: "organize", source: "mate", suggestedBy: "waniyan", enabled: true },
  { id: "organize-toilet-seat", title: "トイレの便座だけ拭く", minutes: 2, category: "organize", source: "mate", suggestedBy: "waniyan", enabled: true },
  { id: "organize-trash-bag", title: "ゴミ袋をひとつまとめる", minutes: 3, category: "organize", source: "mate", suggestedBy: "waniyan", enabled: true },
  { id: "organize-fridge-one", title: "冷蔵庫を1個だけ見直す", minutes: 3, category: "organize", source: "mate", suggestedBy: "waniyan", enabled: true },

  { id: "housework-dish-one", title: "皿を1枚だけ洗う", minutes: 2, category: "housework", source: "mate", suggestedBy: "kumaru", enabled: true },
  { id: "housework-laundry-start", title: "洗濯を回す", minutes: 3, category: "housework", source: "mate", suggestedBy: "kumaru", enabled: true },
  { id: "housework-basket-one", title: "洗濯物を1つだけ畳む", minutes: 2, category: "housework", source: "mate", suggestedBy: "kumaru", enabled: true },
  { id: "housework-shopping-one", title: "買い物メモを1つ書く", minutes: 1, category: "housework", source: "mate", suggestedBy: "kumaru", enabled: true },
  { id: "housework-rice", title: "米を炊く準備だけする", minutes: 3, category: "housework", source: "mate", suggestedBy: "kumaru", enabled: true },
  { id: "housework-stock", title: "日用品の残りを1つ確認する", minutes: 2, category: "housework", source: "mate", suggestedBy: "kumaru", enabled: true },

  { id: "work-mail-one", title: "メールを1通だけ見る", minutes: 3, category: "work", source: "mate", suggestedBy: "shibatarou", enabled: true },
  { id: "work-deadline", title: "期限だけ確認する", minutes: 2, category: "work", source: "mate", suggestedBy: "shibatarou", enabled: true },
  { id: "work-chat-one", title: "チャットを1件だけ返す", minutes: 3, category: "work", source: "mate", suggestedBy: "shibatarou", enabled: true },
  { id: "work-payment", title: "支払い日だけ確認する", minutes: 2, category: "work", source: "mate", suggestedBy: "shibatarou", enabled: true },
  { id: "work-doc-open", title: "書類を開くだけ", minutes: 1, category: "work", source: "mate", suggestedBy: "shibatarou", enabled: true },
  { id: "work-five", title: "5分だけ作業する", minutes: 5, category: "work", source: "mate", suggestedBy: "shibatarou", enabled: true },

  { id: "learning-page", title: "本を1ページ読む", minutes: 3, category: "learning", source: "mate", suggestedBy: "fukurou", enabled: true },
  { id: "learning-code-line", title: "コードを1行眺める", minutes: 2, category: "learning", source: "mate", suggestedBy: "fukurou", enabled: true },
  { id: "learning-word", title: "用語を1つ調べる", minutes: 3, category: "learning", source: "mate", suggestedBy: "fukurou", enabled: true },
  { id: "learning-memo", title: "メモを1つ見返す", minutes: 2, category: "learning", source: "mate", suggestedBy: "fukurou", enabled: true },
  { id: "learning-video", title: "学習動画を1分だけ見る", minutes: 1, category: "learning", source: "mate", suggestedBy: "fukurou", enabled: true },
  { id: "learning-unknown", title: "わからない場所を確認する", minutes: 2, category: "learning", source: "mate", suggestedBy: "fukurou", enabled: true },

  { id: "writing-line", title: "1行だけ書く", minutes: 2, category: "writing", source: "mate", suggestedBy: "nekosenpai", enabled: true },
  { id: "writing-title", title: "タイトルだけ置く", minutes: 2, category: "writing", source: "mate", suggestedBy: "nekosenpai", enabled: true },
  { id: "writing-discomfort", title: "違和感をメモする", minutes: 2, category: "writing", source: "mate", suggestedBy: "nekosenpai", enabled: true },
  { id: "writing-x-draft", title: "X投稿の下書きを作る", minutes: 3, category: "writing", source: "mate", suggestedBy: "nekosenpai", enabled: true },
  { id: "writing-standfm", title: "stand.fmのネタを1つ書く", minutes: 3, category: "writing", source: "mate", suggestedBy: "nekosenpai", enabled: true },
  { id: "writing-note-heading", title: "noteの見出しだけ作る", minutes: 3, category: "writing", source: "mate", suggestedBy: "nekosenpai", enabled: true },

  { id: "creative-vlog", title: "Vlog素材を1本だけ見る", minutes: 5, category: "creative", source: "mate", suggestedBy: "piyori", enabled: true },
  { id: "creative-photo-five", title: "写真を5枚だけ整理する", minutes: 5, category: "creative", source: "mate", suggestedBy: "piyori", enabled: true },
  { id: "creative-app-screen", title: "アプリの画面を1つだけ考える", minutes: 5, category: "creative", source: "mate", suggestedBy: "piyori", enabled: true },
  { id: "creative-code-open", title: "コードを1画面だけ開く", minutes: 3, category: "creative", source: "mate", suggestedBy: "piyori", enabled: true },
  { id: "creative-design-part", title: "デザインを1パーツだけ触る", minutes: 5, category: "creative", source: "mate", suggestedBy: "piyori", enabled: true },
  { id: "creative-idea", title: "アイデアを1つ置く", minutes: 2, category: "creative", source: "mate", suggestedBy: "piyori", enabled: true },

  { id: "care-water", title: "水を飲む", minutes: 1, category: "care", source: "mate", suggestedBy: "azamaru", enabled: true },
  { id: "care-walk-five", title: "5分だけ散歩する", minutes: 5, category: "care", source: "mate", suggestedBy: "azamaru", enabled: true },
  { id: "care-squat-three", title: "スクワットを3回する", minutes: 1, category: "care", source: "mate", suggestedBy: "azamaru", enabled: true },
  { id: "care-pushup-one", title: "腕立てを1回だけする", minutes: 1, category: "care", source: "mate", suggestedBy: "azamaru", enabled: true },
  { id: "care-bath", title: "おふろに入る", minutes: 5, category: "care", source: "mate", suggestedBy: "azamaru", enabled: true },
  { id: "care-stretch", title: "ストレッチを10秒する", minutes: 1, category: "care", source: "mate", suggestedBy: "azamaru", enabled: true },
  { id: "care-sleep", title: "寝る準備を1つする", minutes: 3, category: "care", source: "mate", suggestedBy: "azamaru", enabled: true },
  { id: "care-rest", title: "何もしない時間を取る", minutes: 5, category: "care", source: "mate", suggestedBy: "azamaru", enabled: true },
];

export const defaultTicketDefinitions: TicketDefinition[] = [
  {
    id: "ticket-ice",
    name: "アイスチケット",
    requiredCompletions: 3,
    description: "コンビニアイス1個OK。",
    category: "care",
    costMemo: "300円くらい",
    repeatable: true,
    enabled: true,
  },
  {
    id: "ticket-coffee",
    name: "コーヒーチケット",
    requiredCompletions: 3,
    description: "好きなコーヒーを一杯。",
    category: "care",
    repeatable: true,
    enabled: true,
  },
  {
    id: "ticket-rest",
    name: "何もしないチケット",
    requiredCompletions: 5,
    description: "今夜は何もしなくてOK。",
    category: "care",
    repeatable: true,
    enabled: true,
  },
  {
    id: "ticket-game",
    name: "ゲーム1時間チケット",
    requiredCompletions: 5,
    description: "ゲームを1時間たのしむ。",
    category: "creative",
    repeatable: true,
    enabled: true,
  },
  {
    id: "ticket-sauna",
    name: "サウナチケット",
    requiredCompletions: 10,
    description: "サウナや長めのお風呂へ行ってよし。",
    category: "care",
    repeatable: true,
    enabled: true,
  },
];

export const comments: MateComment[] = [
  { id: "mono-wani", mateId: "waniyan", category: "organize", trigger: "app_open", postType: "mate_monologue", text: "机の端っこだけ空ける日があってもええで。" },
  { id: "mono-kumaru", mateId: "kumaru", category: "housework", trigger: "app_open", postType: "mate_monologue", text: "暮らしは少し回ったら十分だよぉ〜。" },
  { id: "mono-shiba", mateId: "shibatarou", category: "work", trigger: "app_open", postType: "mate_monologue", text: "確認だけでも現実がちょっと軽くなるッ！" },
  { id: "mono-hou", mateId: "fukurou", category: "learning", trigger: "app_open", postType: "mate_monologue", text: "わからない場所を見つけるのも学ぶことですよ。" },
  { id: "mono-mike", mateId: "nekosenpai", category: "writing", trigger: "app_open", postType: "mate_monologue", text: "下書きでいいの。1行置けば始まるわ。" },
  { id: "mono-piyori", mateId: "piyori", category: "creative", trigger: "app_open", postType: "mate_monologue", text: "完成じゃなくて、ちょっとつくるだけでいいぴよ〜。" },
  { id: "mono-aza", mateId: "azamaru", category: "care", trigger: "app_open", postType: "mate_monologue", text: "水を飲むだけでも、体はととのうまる。" },
  { id: "mono-usamaru", mateId: "usamaru", trigger: "app_open", postType: "mate_monologue", text: "迷ったら3分からでOK！ここから始めよ！" },
  { id: "mono-kame", mateId: "kamekichi", trigger: "app_open", postType: "mate_monologue", text: "クエストもチケットも、ゆっくり見ていけばええよぉ。" },

  { id: "start-wani-1", mateId: "waniyan", category: "organize", trigger: "task_start", postType: "mate_reply", text: "全部やらんでええ。床のもん1個拾ったら勝ちや。" },
  { id: "start-wani-2", mateId: "waniyan", category: "organize", trigger: "task_start", postType: "mate_reply", text: "10秒だけいこか。ピカピカはまた今度でええ。" },
  { id: "start-kumaru-1", mateId: "kumaru", category: "housework", trigger: "task_start", postType: "mate_reply", text: "お皿1枚だけ洗おっかぁ。全部じゃなくていいよぉ。" },
  { id: "start-kumaru-2", mateId: "kumaru", category: "housework", trigger: "task_start", postType: "mate_reply", text: "洗濯、回すだけでも未来の自分が助かるよぉ〜。" },
  { id: "start-shiba-1", mateId: "shibatarou", category: "work", trigger: "task_start", postType: "mate_reply", text: "期限だけ確認しよ！やるかどうかはそのあとでいいッ！" },
  { id: "start-shiba-2", mateId: "shibatarou", category: "work", trigger: "task_start", postType: "mate_reply", text: "5分だけ仕事モード入ろッ！5分後に逃げてもセーフッ！" },
  { id: "start-hou-1", mateId: "fukurou", category: "learning", trigger: "task_start", postType: "mate_reply", text: "今日は1ページだけ読みましょう。少しでも、知識は残りますよ。" },
  { id: "start-hou-2", mateId: "fukurou", category: "learning", trigger: "task_start", postType: "mate_reply", text: "コードは1行眺めるだけでも学ぶことです。焦らなくていいですよ。" },
  { id: "start-mike-1", mateId: "nekosenpai", category: "writing", trigger: "task_start", postType: "mate_reply", text: "いきなり名文を書こうとするから止まるのよ。下書きでいいの。" },
  { id: "start-mike-2", mateId: "nekosenpai", category: "writing", trigger: "task_start", postType: "mate_reply", text: "その違和感、メモしときなさい。あとで記事になるかもね。" },
  { id: "start-piyori-1", mateId: "piyori", category: "creative", trigger: "task_start", postType: "mate_reply", text: "完成までいけなくても、素材をチェックだけでいいぴよ〜。" },
  { id: "start-piyori-2", mateId: "piyori", category: "creative", trigger: "task_start", postType: "mate_reply", text: "今日は1パーツだけ触るぴよ。作品は小さい羽からできるぴよ〜。" },
  { id: "start-aza-1", mateId: "azamaru", category: "care", trigger: "task_start", postType: "mate_reply", text: "水飲んだ？えらいまる。生命維持、できてるまる。" },
  { id: "start-aza-2", mateId: "azamaru", category: "care", trigger: "task_start", postType: "mate_reply", text: "おふろ入れたら勝ちまる。今日は回復クエストでいいまる。" },

  { id: "start-usamaru", mateId: "usamaru", trigger: "task_start", postType: "mate_reply", text: "開始できた！まず押せたのがえらい！", minAffinity: 4 },
  { id: "start-kame", mateId: "kamekichi", trigger: "task_start", postType: "mate_reply", text: "短い時間でええよぉ。戻れる場所があるのは安心やねぇ。", minAffinity: 4 },

  { id: "progress-wani", mateId: "waniyan", category: "organize", trigger: "progress", postType: "mate_reply", text: "まだ続いてるやん。ええ粘りしてるで。" },
  { id: "progress-kumaru", mateId: "kumaru", category: "housework", trigger: "progress", postType: "mate_reply", text: "途中まででも生活はちゃんと回ってるよぉ〜。" },
  { id: "progress-shiba", mateId: "shibatarou", category: "work", trigger: "progress", postType: "mate_reply", text: "ここまで見られたなら十分ッ！次は1個だけでOKッ！" },
  { id: "progress-hou", mateId: "fukurou", category: "learning", trigger: "progress", postType: "mate_reply", text: "ここで一度、次の一動作だけに視点を戻しましょう。" },
  { id: "progress-mike", mateId: "nekosenpai", category: "writing", trigger: "progress", postType: "mate_reply", text: "消さずに残してるだけでも、まあ悪くないわね。" },
  { id: "progress-piyori", mateId: "piyori", category: "creative", trigger: "progress", postType: "mate_reply", text: "試してる途中がいちばん大事ぴよ〜。" },
  { id: "progress-aza", mateId: "azamaru", category: "care", trigger: "progress", postType: "mate_reply", text: "続いてるだけでえらいまる。力は抜くまる。" },

  { id: "complete-wani", mateId: "waniyan", trigger: "complete", postType: "mate_reply", text: "ええやん。今の達成、ちゃんと自分の手柄にしときや。" },
  { id: "complete-kumaru", mateId: "kumaru", trigger: "complete", postType: "mate_reply", text: "できたねぇ。暮らしが少し回ったよぉ〜。" },
  { id: "complete-shiba", mateId: "shibatarou", trigger: "complete", postType: "mate_reply", text: "できたッ！今日の現実対応、ちゃんと前に進んだッ！" },
  { id: "complete-hou", mateId: "fukurou", trigger: "complete", postType: "mate_reply", text: "完了です。小さく区切れた良い記録ですよ。" },
  { id: "complete-mike", mateId: "nekosenpai", trigger: "complete", postType: "mate_reply", text: "やるじゃない。まあ、できると思ってたけど。" },
  { id: "complete-piyori", mateId: "piyori", trigger: "complete", postType: "mate_reply", text: "できたぴよ〜。小さい試作もちゃんとつくった証ぴよ。" },
  { id: "complete-aza", mateId: "azamaru", trigger: "complete", postType: "mate_reply", text: "できたまる。今日は体と心がちょっとととのったまる。" },

  { id: "partial-wani", mateId: "waniyan", trigger: "partial", postType: "mate_reply", text: "少し進んだならええやん。ゼロから動かしたんは事実や。" },
  { id: "partial-kumaru", mateId: "kumaru", trigger: "partial", postType: "mate_reply", text: "ちょっとできたなら十分だよぉ。また続きからでいいよぉ〜。" },
  { id: "partial-shiba", mateId: "shibatarou", trigger: "partial", postType: "mate_reply", text: "少し見たならOKッ！次に戻る場所ができたッ！" },
  { id: "partial-hou", mateId: "fukurou", trigger: "partial", postType: "mate_reply", text: "残りは次回の開始点です。今日は進んだ部分だけ見ましょう。" },
  { id: "partial-mike", mateId: "nekosenpai", trigger: "partial", postType: "mate_reply", text: "全部じゃなくてもいいでしょ。途中まででも書いた側よ。" },
  { id: "partial-piyori", mateId: "piyori", trigger: "partial", postType: "mate_reply", text: "途中でも素材になるぴよ〜。消さなくていいぴよ。" },
  { id: "partial-aza", mateId: "azamaru", trigger: "partial", postType: "mate_reply", text: "少しできたまる。体にはそれで十分な日もあるまる。" },

  { id: "interrupted-wani", mateId: "waniyan", trigger: "interrupted", postType: "mate_reply", text: "中断も作業のうちや。いったん置いとこ。" },
  { id: "interrupted-kumaru", mateId: "kumaru", trigger: "interrupted", postType: "mate_reply", text: "止まっても大丈夫だよぉ。暮らしはまた戻れるよぉ〜。" },
  { id: "interrupted-shiba", mateId: "shibatarou", trigger: "interrupted", postType: "mate_reply", text: "中断でも記録は残ったッ！また見ればOKッ！" },
  { id: "interrupted-hou", mateId: "fukurou", trigger: "interrupted", postType: "mate_reply", text: "止めたことも、状況を見た結果です。" },
  { id: "interrupted-mike", mateId: "nekosenpai", trigger: "interrupted", postType: "mate_reply", text: "邪魔が入ったなら仕方ないでしょ。自分を責めなくていいわ。" },
  { id: "interrupted-piyori", mateId: "piyori", trigger: "interrupted", postType: "mate_reply", text: "中断しても試した事実は残るぴよ〜。" },
  { id: "interrupted-aza", mateId: "azamaru", trigger: "interrupted", postType: "mate_reply", text: "止まったなら休むまる。また戻れたらそれでいいまる。" },

  { id: "failed-wani", mateId: "waniyan", trigger: "failed", postType: "mate_reply", text: "無理な日はある。負け判定を急がんでええ。" },
  { id: "failed-kumaru", mateId: "kumaru", trigger: "failed", postType: "mate_reply", text: "今日は回らない日だったねぇ。生活は明日も続くよぉ〜。" },
  { id: "failed-shiba", mateId: "shibatarou", trigger: "failed", postType: "mate_reply", text: "無理だった日もあるッ！戻ってきたら再開できるッ！" },
  { id: "failed-hou", mateId: "fukurou", trigger: "failed", postType: "mate_reply", text: "失敗ではなく、今日の条件では難しかったという記録です。" },
  { id: "failed-mike", mateId: "nekosenpai", trigger: "failed", postType: "mate_reply", text: "無理だった？そういう日もあるでしょ。また来たら相手するわ。" },
  { id: "failed-piyori", mateId: "piyori", trigger: "failed", postType: "mate_reply", text: "今日は飛ばない日ぴよ〜。羽を休めるぴよ。" },
  { id: "failed-aza", mateId: "azamaru", trigger: "failed", postType: "mate_reply", text: "無理だったまる。生きて戻ってきただけで十分まる。" },
];
